require "digest/md5"
require_relative "features/support/libs/mongo"

def to_md5(pass)
  return Digest::MD5.hexdigest(pass)
end

task :local_seeds do
  CONFIG = YAML.load_file(File.join(Dir.pwd, "features/support/config/local.yml"))
  users = [
    { name: "Sandra", email: "sandra@yahoo.com", password: to_md5("abc123") },
    { name: "Pete", email: "pete@yahoo.com", password: to_md5("abc123") },
    { name: "Pete", email: "pete@gmail.com", password: to_md5("abc123") },
    { name: "Sandra", email: "sandrinha@yahoo.com", password: to_md5("abc123") },
    { name: "Pete Anunciante", email: "anunciante@yahoo.com", password: to_md5("abc123") },
    { name: "Pete Locataria", email: "locataria@yahoo.com", password: to_md5("abc123") },
  ]

  MongoDB.new.drop_danger
  MongoDB.new.insert_users(users)

 sh "cucumber -p jenkins"
end

task :hmg_seeds do
  CONFIG = YAML.load_file(File.join(Dir.pwd, "features/support/config/hmg.yml"))
  users = [
    { name: "Sandra", email: "sandra@yahoo.com", password: to_md5("abc123") },
    { name: "Pete", email: "pete@yahoo.com", password: to_md5("abc123") },
    { name: "Pete", email: "pete@gmail.com", password: to_md5("abc123") },
    { name: "Sandra", email: "sandrinha@yahoo.com", password: to_md5("abc123") },
    { name: "Pete Anunciante", email: "anunciante@yahoo.com", password: to_md5("abc123") },
    { name: "Pete Locataria", email: "locataria@yahoo.com", password: to_md5("abc123") },
  ]

  MongoDB.new.drop_danger
  MongoDB.new.insert_users(users)
end
